### PR TITLE
Updated isHTMLSafe import, fixes #698

### LINKED ISSUE #698: After update to ember 3.27.5 there is an error: Uncaught TypeError: (0 , _string.isHTMLSafe) is not a function
Fails on any page with validation

```
Uncaught TypeError: (0 , _string.isHTMLSafe) is not a function
    at unwrapString (utils.js:36)
    at Class.createErrorMessage (base.js:208)
    at Class.validate (ember-validator.js:14)
    at factory.js:366
    at factory.js:452
    at Array.map (<anonymous>)
    at generateValidationResultsFor (factory.js:430)
    at Class.<anonymous> (factory.js:365)
    at Class.<anonymous> (cycle-breaker.js:26)
    at index.js:1935
```
In `utils.js (ember-cp-validations/utils/utils)` fails on this line:

```
function unwrapString(s) {
    if ((0, _string.isHTMLSafe)(s)) { // <<<------ fails here
      return s.toString();
    }

    return s;
  }
```

How to fix this issue? Thank you

### Environment

- Ember Version: 3.27.5
- Ember CLI Version: 3.27
- Ember CP Validations Version: 4.0.0-beta.12

### Steps to Reproduce
Any page where validation occures

### PR DESCRIPTION
**Pull request by lolmaus**
Resolves #698.

Changes proposed:

 - Update the `isHTMLSafe` import to use the [new import path](https://api.emberjs.com/ember/release/functions/@ember/template/isHTMLSafe).

Tasks:

- Testing
    - [x] ~~Added test case(s)~~ Already covered by exisisting test cases
    - [ ] Udpate test matrix maybe?
- Documentation
    - [ ] Update EmberJS version requirement
    - [ ] Add note for support of older Ember versions (e. g. use an older version of the addon or add a polyfill?)

CC @simonihmig

### CODE REVIEW

**Comment by lolmaus** [comment]
@offirgolan Please advise or take over.

**Review by rahulk94 — APPROVED** [review]
These changes LGTM, the IDE gitignore changes are somewhat unrelated but there's more value in getting this merged + a new alpha out than arguing over that.

**Comment by Baukereg** [comment]
Any chance this will be merged soon?

**Comment by steveclifton** [comment]
Yip can we get this merged too please :) or Happy to put into a separate PR without the `.gitignore` file changes

**Comment by Baukereg** [comment]
@steveclifton Looks like this project is abandoned. But you can depend on this fix like this:

```
"ember-cp-validations": "lolmaus/ember-cp-validations.git#issue-698-isHTMLSafe"
```

**Comment by fsmanuel** [comment]
@lolmaus that should be fixed in the new beta release.

**Comment by lolmaus** [comment]
image

**Pull request closed without merging**
